-- ============================================================
-- PAUL MOTOR CO. CRM — Production database setup
-- Run against Neon or Supabase Postgres (SQL editor or psql).
-- Safe to re-run: uses IF NOT EXISTS / idempotent DDL.
-- ============================================================


-- >>> 0001_auth.sql

-- Better Auth schema (identity + sessions for "Sign in with Grok").
--
-- Generated by the Better Auth CLI for its Postgres adapter — DO NOT EDIT by
-- hand. `@/lib/auth/server` runs Better Auth against these tables when
-- DATABASE_URL is set. The columns are camelCase and MUST stay double-quoted so
-- Postgres preserves the case Better Auth queries by.
--
-- Migrations in this folder are the single source of truth for your schema. They
-- apply to Neon during the Vercel build (`npm run build`) and to the local
-- PGLite fallback automatically on startup, so dev matches production. Applied
-- files are recorded by name in `_migrations` and NEVER run again.
--
-- Put YOUR app's schema in NEW ordered files (0002_*.sql, 0003_*.sql, …), never
-- in this one. For app tables, prefer snake_case and give per-user tables a
-- `user_id TEXT NOT NULL` column (TEXT, not UUID — the preview dev user id is
-- the string 'dev-user'), then scope every query to the authenticated user
-- server-side (see the `neon` + `auth` skills and src/lib/auth/verify.server.ts).

create table if not exists "user" (
  "id" text not null primary key,
  "name" text not null,
  "email" text not null unique,
  "emailVerified" boolean not null,
  "image" text,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create table if not exists "session" (
  "id" text not null primary key,
  "expiresAt" timestamptz not null,
  "token" text not null unique,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz not null,
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references "user" ("id") on delete cascade
);

create table if not exists "account" (
  "id" text not null primary key,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references "user" ("id") on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope" text,
  "password" text,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz not null
);

create table if not exists "verification" (
  "id" text not null primary key,
  "identifier" text not null,
  "value" text not null,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create index if not exists "session_userId_idx" on "session" ("userId");
create index if not exists "account_userId_idx" on "account" ("userId");
create index if not exists "verification_identifier_idx" on "verification" ("identifier");


-- >>> 0002_crm.sql

-- Paul Motor Company CRM — luxury & exotic vehicle leasing / sales (Montréal)

create table if not exists profiles (
  id text primary key,
  user_id text unique,
  email text not null unique,
  name text not null,
  role text not null check (role in ('admin', 'rep', 'broker')),
  active boolean not null default true,
  phone text,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on profiles (role);
create index if not exists profiles_user_id_idx on profiles (user_id);

create table if not exists inventory (
  id text primary key,
  year int not null,
  make text not null,
  model text not null,
  trim text,
  vin text,
  stock_number text,
  price numeric,
  mileage int,
  exterior_color text,
  interior_color text,
  body_type text,
  transmission text,
  fuel_type text,
  status text not null default 'available'
    check (status in ('available', 'reserved', 'sold', 'incoming')),
  source text not null default 'manual'
    check (source in ('manual', 'website', 'autotrader')),
  external_url text,
  image_url text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists inventory_make_model_idx on inventory (make, model);
create index if not exists inventory_status_idx on inventory (status);

create table if not exists leads (
  id text primary key,
  name text not null,
  phone text,
  email text,
  source text not null default 'phone'
    check (source in ('phone', 'walk_in', 'email', 'broker', 'other', 'web')),
  notes text,
  vehicle_interest text,
  inventory_id text references inventory (id) on delete set null,
  assigned_to text references profiles (id) on delete set null,
  stage text not null default 'new'
    check (stage in ('new', 'contacted', 'test_drive', 'quote_sent', 'ready_bc', 'won', 'lost')),
  stage_entered_at timestamptz not null default now(),
  quote_sent boolean not null default false,
  quote_sent_at timestamptz,
  quote_link text,
  quote_notes text,
  google_review_status text not null default 'not_requested'
    check (google_review_status in ('not_requested', 'requested', 'received')),
  google_review_at timestamptz,
  google_review_link text,
  estimated_value numeric,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_stage_idx on leads (stage);
create index if not exists leads_assigned_to_idx on leads (assigned_to);
create index if not exists leads_created_at_idx on leads (created_at desc);

create table if not exists lead_activities (
  id text primary key,
  lead_id text not null references leads (id) on delete cascade,
  kind text not null default 'note',
  body text not null,
  created_by text,
  created_by_name text,
  created_at timestamptz not null default now()
);

create index if not exists lead_activities_lead_idx on lead_activities (lead_id, created_at desc);

create table if not exists test_drives (
  id text primary key,
  lead_id text not null references leads (id) on delete cascade,
  inventory_id text references inventory (id) on delete set null,
  scheduled_at timestamptz not null,
  duration_minutes int not null default 30,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'completed', 'no_show', 'cancelled')),
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists test_drives_scheduled_idx on test_drives (scheduled_at);
create index if not exists test_drives_lead_idx on test_drives (lead_id);


-- >>> 0003_crm_v2_reset.sql

-- If an older 0002 CRM schema is already applied (pre-luxury rebuild), drop and
-- recreate is handled only for fresh DBs. This migration is a no-op safety net
-- for environments that already have the new tables from 0002.
-- Intentionally empty: new 0002 defines the full Paul Motor Company schema.
select 1;


-- >>> 0004_lead_type_quote_pdf.sql

-- Lead type (inventory sale vs lease quote) + PDF quote attachment storage

alter table leads add column if not exists lead_type text not null default 'inventory'
  check (lead_type in ('inventory', 'lease'));

alter table leads add column if not exists quote_pdf_name text;
alter table leads add column if not exists quote_pdf_data text;

-- Email paste / raw source body kept for audit
alter table leads add column if not exists source_email_raw text;

create index if not exists leads_lead_type_idx on leads (lead_type);


-- Migration tracking (matches scripts/migrate.mjs)
CREATE TABLE IF NOT EXISTS _migrations (
  name TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO _migrations (name) VALUES ('0001_auth.sql') ON CONFLICT (name) DO NOTHING;
INSERT INTO _migrations (name) VALUES ('0002_crm.sql') ON CONFLICT (name) DO NOTHING;
INSERT INTO _migrations (name) VALUES ('0003_crm_v2_reset.sql') ON CONFLICT (name) DO NOTHING;
INSERT INTO _migrations (name) VALUES ('0004_lead_type_quote_pdf.sql') ON CONFLICT (name) DO NOTHING;
