/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ComplianceOpsRouteImport } from './routes/compliance-ops'
import { Route as DataAnalysisRouteImport } from './routes/data-analysis'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as CreditAppTokenRouteImport } from './routes/credit-app.$token'
import { Route as CreditDocsTokenRouteImport } from './routes/credit-docs.$token'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as ServiceEstimateTokenRouteImport } from './routes/service-estimate.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronImportEmailsRouteImport } from './routes/api/cron/import-emails'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as ApiCronRemindersDailyRouteImport } from './routes/api/cron/reminders-daily'
import { Route as ApiCronRemindersHourlyRouteImport } from './routes/api/cron/reminders-hourly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceOpsRoute = ComplianceOpsRouteImport.update({
  id: '/compliance-ops',
  path: '/compliance-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAnalysisRoute = DataAnalysisRouteImport.update({
  id: '/data-analysis',
  path: '/data-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditAppTokenRoute = CreditAppTokenRouteImport.update({
  id: '/credit-app/$token',
  path: '/credit-app/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditDocsTokenRoute = CreditDocsTokenRouteImport.update({
  id: '/credit-docs/$token',
  path: '/credit-docs/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)
const ServiceEstimateTokenRoute = ServiceEstimateTokenRouteImport.update({
  id: '/service-estimate/$token',
  path: '/service-estimate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronImportEmailsRoute = ApiCronImportEmailsRouteImport.update({
  id: '/api/cron/import-emails',
  path: '/api/cron/import-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersDailyRoute = ApiCronRemindersDailyRouteImport.update({
  id: '/api/cron/reminders-daily',
  path: '/api/cron/reminders-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersHourlyRoute = ApiCronRemindersHourlyRouteImport.update({
  id: '/api/cron/reminders-hourly',
  path: '/api/cron/reminders-hourly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRoute
  '/compliance-ops': typeof ComplianceOpsRoute
  '/data-analysis': typeof DataAnalysisRoute
  '/dms': typeof DmsRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/quote': typeof QuoteRoute
  '/service': typeof ServiceRoute
  '/tasks': typeof TasksRoute
  '/api/health': typeof ApiHealthRoute
  '/credit-app/$token': typeof CreditAppTokenRoute
  '/credit-docs/$token': typeof CreditDocsTokenRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/service-estimate/$token': typeof ServiceEstimateTokenRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/import-emails': typeof ApiCronImportEmailsRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/reminders-daily': typeof ApiCronRemindersDailyRoute
  '/api/cron/reminders-hourly': typeof ApiCronRemindersHourlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRoute
  '/compliance-ops': typeof ComplianceOpsRoute
  '/data-analysis': typeof DataAnalysisRoute
  '/dms': typeof DmsRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/quote': typeof QuoteRoute
  '/service': typeof ServiceRoute
  '/tasks': typeof TasksRoute
  '/api/health': typeof ApiHealthRoute
  '/credit-app/$token': typeof CreditAppTokenRoute
  '/credit-docs/$token': typeof CreditDocsTokenRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/service-estimate/$token': typeof ServiceEstimateTokenRoute
  '/leads': typeof LeadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/import-emails': typeof ApiCronImportEmailsRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/reminders-daily': typeof ApiCronRemindersDailyRoute
  '/api/cron/reminders-hourly': typeof ApiCronRemindersHourlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRoute
  '/compliance-ops': typeof ComplianceOpsRoute
  '/data-analysis': typeof DataAnalysisRoute
  '/dms': typeof DmsRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/quote': typeof QuoteRoute
  '/service': typeof ServiceRoute
  '/tasks': typeof TasksRoute
  '/api/health': typeof ApiHealthRoute
  '/credit-app/$token': typeof CreditAppTokenRoute
  '/credit-docs/$token': typeof CreditDocsTokenRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/service-estimate/$token': typeof ServiceEstimateTokenRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/import-emails': typeof ApiCronImportEmailsRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/reminders-daily': typeof ApiCronRemindersDailyRoute
  '/api/cron/reminders-hourly': typeof ApiCronRemindersHourlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/capture'
    | '/compliance-ops'
    | '/data-analysis'
    | '/dms'
    | '/help'
    | '/inventory'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/quote'
    | '/service'
    | '/tasks'
    | '/api/health'
    | '/credit-app/$token'
    | '/credit-docs/$token'
    | '/leads/$leadId'
    | '/service-estimate/$token'
    | '/leads/'
    | '/api/auth/$'
    | '/api/cron/import-emails'
    | '/api/cron/reminders'
    | '/api/cron/reminders-daily'
    | '/api/cron/reminders-hourly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/capture'
    | '/compliance-ops'
    | '/data-analysis'
    | '/dms'
    | '/help'
    | '/inventory'
    | '/login'
    | '/pipeline'
    | '/quote'
    | '/service'
    | '/tasks'
    | '/api/health'
    | '/credit-app/$token'
    | '/credit-docs/$token'
    | '/leads/$leadId'
    | '/service-estimate/$token'
    | '/leads'
    | '/api/auth/$'
    | '/api/cron/import-emails'
    | '/api/cron/reminders'
    | '/api/cron/reminders-daily'
    | '/api/cron/reminders-hourly'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/capture'
    | '/compliance-ops'
    | '/data-analysis'
    | '/dms'
    | '/help'
    | '/inventory'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/quote'
    | '/service'
    | '/tasks'
    | '/api/health'
    | '/credit-app/$token'
    | '/credit-docs/$token'
    | '/leads/$leadId'
    | '/service-estimate/$token'
    | '/leads/'
    | '/api/auth/$'
    | '/api/cron/import-emails'
    | '/api/cron/reminders'
    | '/api/cron/reminders-daily'
    | '/api/cron/reminders-hourly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  CaptureRoute: typeof CaptureRoute
  ComplianceOpsRoute: typeof ComplianceOpsRoute
  DataAnalysisRoute: typeof DataAnalysisRoute
  DmsRoute: typeof DmsRoute
  HelpRoute: typeof HelpRoute
  InventoryRoute: typeof InventoryRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  QuoteRoute: typeof QuoteRoute
  ServiceRoute: typeof ServiceRoute
  TasksRoute: typeof TasksRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CreditAppTokenRoute: typeof CreditAppTokenRoute
  CreditDocsTokenRoute: typeof CreditDocsTokenRoute
  ServiceEstimateTokenRoute: typeof ServiceEstimateTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronImportEmailsRoute: typeof ApiCronImportEmailsRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiCronRemindersDailyRoute: typeof ApiCronRemindersDailyRoute
  ApiCronRemindersHourlyRoute: typeof ApiCronRemindersHourlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-ops': {
      id: '/compliance-ops'
      path: '/compliance-ops'
      fullPath: '/compliance-ops'
      preLoaderRoute: typeof ComplianceOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-analysis': {
      id: '/data-analysis'
      path: '/data-analysis'
      fullPath: '/data-analysis'
      preLoaderRoute: typeof DataAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-app/$token': {
      id: '/credit-app/$token'
      path: '/credit-app/$token'
      fullPath: '/credit-app/$token'
      preLoaderRoute: typeof CreditAppTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-docs/$token': {
      id: '/credit-docs/$token'
      path: '/credit-docs/$token'
      fullPath: '/credit-docs/$token'
      preLoaderRoute: typeof CreditDocsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/service-estimate/$token': {
      id: '/service-estimate/$token'
      path: '/service-estimate/$token'
      fullPath: '/service-estimate/$token'
      preLoaderRoute: typeof ServiceEstimateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/import-emails': {
      id: '/api/cron/import-emails'
      path: '/api/cron/import-emails'
      fullPath: '/api/cron/import-emails'
      preLoaderRoute: typeof ApiCronImportEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders-daily': {
      id: '/api/cron/reminders-daily'
      path: '/api/cron/reminders-daily'
      fullPath: '/api/cron/reminders-daily'
      preLoaderRoute: typeof ApiCronRemindersDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders-hourly': {
      id: '/api/cron/reminders-hourly'
      path: '/api/cron/reminders-hourly'
      fullPath: '/api/cron/reminders-hourly'
      preLoaderRoute: typeof ApiCronRemindersHourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  CaptureRoute: CaptureRoute,
  ComplianceOpsRoute: ComplianceOpsRoute,
  DataAnalysisRoute: DataAnalysisRoute,
  DmsRoute: DmsRoute,
  HelpRoute: HelpRoute,
  InventoryRoute: InventoryRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  QuoteRoute: QuoteRoute,
  ServiceRoute: ServiceRoute,
  TasksRoute: TasksRoute,
  ApiHealthRoute: ApiHealthRoute,
  CreditAppTokenRoute: CreditAppTokenRoute,
  CreditDocsTokenRoute: CreditDocsTokenRoute,
  ServiceEstimateTokenRoute: ServiceEstimateTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronImportEmailsRoute: ApiCronImportEmailsRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiCronRemindersDailyRoute: ApiCronRemindersDailyRoute,
  ApiCronRemindersHourlyRoute: ApiCronRemindersHourlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
